### ISSUE TITLE
Variable length of shifting per individual gear

### ISSUE THREAD

**Issue by AlexPl81** [lalilaloe/speedshift#3]
Hi, this is an awesome project, thank you for sharing! I'm working on an open source trike and I have a Shimano Alfine 11 gear hub to work with. Shimano hubs have certain gears that require more pull, like most of the gears are switched with 5mm pull, while several other gears are 6.4 mm. Unfortunately my understanding of the code is not sufficient to determine whether it is possible to have such setup with simply putting the values for each gear somewhere in the code, or all gears are defined by a single variable? These hubs are very sensitive to the precision of switching, so electronic shifting like this is the best way to shift them and prolong their life.

**Comment by lalilaloe** [comment]
Can you elaborate on how you operate the shifting? Is this also done with a servo?
